### PR TITLE
add browser compat report

### PR DESCRIPTION
**Pull request by schalkneethling**
Add browser compatibility report copy and link to the landing page.

@chrisdavidmills I notice that the current PDF is hosted on S3 so, I assume this one will need to be hosted there as well.
I am guessing @limed will know how to get it into the relevant bucket.

I added a link to the expected location but, we can change it if it will be different.

part of #42

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
Looking mostly good @schalkneethling . I have a couple of requests:

1. I think it'd look better if the image was vertically centered in the box, alongside the two links.
2. The spacing between the headings and the links looks a bit off. It'd look better if the spacing was all equal.

**Comment by schalkneethling** [comment]
> Looking mostly good @schalkneethling . I have a couple of requests:
> 
> 1. I think it'd look better if the image was vertically centered in the box, alongside the two links.
> 2. The spacing between the headings and the links looks a bit off. It'd look better if the spacing was all equal.

Sounds good. I was not sure if I should mess with the existing site 😄  I will update this with your suggestions.

We then also need to make a decision around how we want to handle the PDF. If there was no real reason to host it separately on S3, I would recommend we just stick it into the assets folder of the project and serve as part of the site.

Let me know your thoughts.

**Comment by chrisdavidmills** [comment]
> We then also need to make a decision around how we want to handle the PDF. If there was no real reason to host it separately on S3, I would recommend we just stick it into the assets folder of the project and serve as part of the site.

Sounds fine to me.

**Review by alshamiri5 — APPROVED** [review]

**Comment by schalkneethling** [comment]
@chrisdavidmills Do we know who maintains the infra for this site? It looks like it might be automatically deployed on merges to master: https://github.com/mdn/insights/blob/master/bin/s3-sync.sh

**Comment by chrisdavidmills** [comment]
@schalkneethling I have no idea, I'm afraid.

**Comment by schalkneethling** [comment]
> @schalkneethling I have no idea, I'm afraid.

I have made updates to the layout per your suggestions. I also linked the PDF and included it in the `assets` folder but, when running it via the webpack dev server I get a 404 locally. Perhaps the dev server cannot serve PDF files or requires some config change? @limed @escattone

**Comment by chrisdavidmills** [comment]
Layout changes look great; thanks @schalkneethling !

**Comment by limed** [comment]
> > @schalkneethling I have no idea, I'm afraid.
> 
> I have made updates to the layout per your suggestions. I also linked the PDF and included it in the `assets` folder but, when running it via the webpack dev server I get a 404 locally. Perhaps the dev server cannot serve PDF files or requires some config change? @limed @escattone
> 
> Or maybe it will just work when deployed to S3?

Hi @schalkneethling I can upload the file to S3 but the references to the file might need to point to S3 based on the PR

I grabbed the PDF from this PR and have uploaded it

**Comment by schalkneethling** [comment]
> The name of the s3 bucket can change if its not suitable and I am alright with naming it whatever it needs to be fore hosting the static pdf assets.

Thank you @limed - this works!

**Pull request merged**
