### PR TITLE
Replace SVG's with correct ones (fixes spaces in text bug)

### PR DESCRIPTION
**Pull request by chrisevouk**
Replace SVG's with correct ones (fixes spaces in text bug)

re:
> The question is if its easier to just replace the SVG files with the new ones

We should be able to just replace them. The one's for 2020 would all go here:
https://github.com/mdn/insights/tree/master/public/reports/assets/images/web-developer-needs-assessment-2020

### CODE REVIEW

**Comment by foolip** [comment]
Is there a staging instance to preview this?

**Comment by chrisevouk** [comment]
https://deploy-preview-101--brave-poitras-1ebc93.netlify.app/reports/assets/images/web-developer-needs-assessment-2020/Responses-By-Subcategory_Gender.svg

Yes so see SVG at above staging URL is ok and came from PR 101, but come to production and there’s spacing within text.

https://insights.developer.mozilla.org/reports/assets/images/web-developer-needs-assessment-2020/Responses-By-Subcategory_Gender.svg

Schalk commented that this may be as a result of the master branch being renamed to main very recently (which caught me out at first with the initial PR for links).

**Comment by foolip** [comment]
The linked SVG looks good. Are all SVGs regenerated, or does someone need to scroll through the report and check each one to be sure everything's OK now?

**Comment by chrisevouk** [comment]
That looks ok to me now.

I’ve noticed some items that look weird (red text when it’s a red bar) but I’ll have to ask the designer if that was intentional.  Might just be hard for me to read the text with my laptop going into night shift colour mode.

**Review by schalkneethling — APPROVED** [review]

**Pull request merged**
