### PR TITLE
PR resolving missing missing links in MDN Browser Compatibility Report 2020

### PR DESCRIPTION
**Pull request by chrisevouk**
@foolip @chrisdavidmills @schalkneethling
PR ready to go that will resolve missing missing links in MDN Browser Compatibility Report 2020

Along with missing links some fonts also fixed by @samuelbirch.

Thanks

Chris

### CODE REVIEW

**Review by schalkneethling — APPROVED** [review]
Thank you. Let's get this on a server so folks can double check

**Comment by foolip** [comment]
Will this be deployed to https://insights.developer.mozilla.org/reports/mdn-browser-compatibility-report-2020.html or where can I check?

**Comment by schalkneethling** [comment]
> Will this be deployed to https://insights.developer.mozilla.org/reports/mdn-browser-compatibility-report-2020.html or where can I check?

You can see it on staging here: https://brave-poitras-1ebc93.netlify.app/

**Comment by foolip** [comment]
I've taken a scroll through https://brave-poitras-1ebc93.netlify.app/reports/mdn-browser-compatibility-report-2020.html and it looks good, I can't spot anything I know was supposed to be a link which now isn't.

**Comment by chrisevouk** [comment]
This is not a link issue, the SVG’s were replaced and the new ones haven’t come across.  The links are fine in this version.

**Comment by foolip** [comment]
@chrisevouk I don't understand, isn't this PR precisely about fixing links?

**Comment by chrisevouk** [comment]
There was 2.  The first one fixed links.

The second one replaced SVG’s as we had some defective ones.

**Comment by chrisevouk** [comment]
I’ve created a fresh one:
https://github.com/mdn/insights/pull/106

**Comment by chrisevouk** [comment]
That said.  The previous PR worked to sort out the staging SVG’s.  We just only got the link fixes on the ship to production.

**Pull request merged**
