### PR TITLE
adding accessible HTML version of web testing report

### PR DESCRIPTION
**Pull request by chrisdavidmills**
We had a request to create an accessible HTML version of the web testing report. I didn't have much time to spend on this, so I grabbed the HTML from the Google Doc version, and plugged the existing CSS into it. Needless to say, it is a bit scrappy, and not the prettiest, but it is accessible (I tested it, and there were few errors).

Does this look OK enough to put on the site?

### CODE REVIEW

**Review by escattone — APPROVED** [review]
Thanks @chrisdavidmills! I'll take care of deploying this once @schalkneethling is happy.

**Comment by schalkneethling** [comment]
@chrisdavidmills This is not bad but, I think we should perhaps clean it up a bit. I am going to merge this and will take some time tomorrow to do a once-over and clean it up a bit so it's a bit closer to the other HTML reports. Thanks so much!

**Review by schalkneethling — APPROVED** [review]
Good for a v0.5 😄

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills This is not bad but, I think we should perhaps clean it up a bit. I am going to merge this and will take some time tomorrow to do a once-over and clean it up a bit so it's a bit closer to the other HTML reports. Thanks so much!

Cheers mate! I just ran out of time to do any more.

**Comment by escattone** [comment]
Thanks @schalkneethling! Just let me know when you've merged your updated version, and I'll take care of deploying it.

**Pull request merged**
